import type { Product, ProductFaq } from './products';

const commonFaqs = (name: string, safetyNote: string): ProductFaq[] => [
  {
    question: `What do I receive with the ${name}?`,
    answer: 'You receive one editable Excel workbook with a working Record sheet, a completed example row, built-in instructions, clear input cells, and space for 40 live records. The file can be duplicated for each project or property.',
  },
  {
    question: 'Can I add my company name and project references?',
    answer: 'Yes. The workbook is fully editable. Add your company details, project references, drawing numbers, photo references, and any extra columns required by your client or inspection plan.',
  },
  {
    question: 'Is this an official certificate or a substitute for competent inspection?',
    answer: `No. ${safetyNote} The workbook provides a clear structure for recording work and evidence; it does not approve, certify, design, inspect, or make an installation safe.`,
  },
  {
    question: 'How is the file delivered?',
    answer: 'After payment, Stripe directs you to the download. Save the original file, then create a separate copy for each project. This is a one-time purchase with no subscription.',
  },
];

export const jobPacks: Product[] = [
  {
    slug: 'ufh-screed-dry-out-log-template',
    title: 'Underfloor Heating Screed Dry-Out Log Template',
    shortDescription: 'Editable Excel log for recording the UFH screed warm-up programme, daily temperatures, pressure, observations, and installer initials.',
    fullDescription: 'Record the heating-up stage without piecing together notes from emails, photographs, and scraps of paper. This workbook gives heating installers and screed contractors one clear daily record for flow, return, floor and room temperatures, target temperature, system pressure, observations, and sign-off.',
    category: 'Heating Records',
    categorySlug: 'heating-records',
    price: 19,
    badge: 'Best first product',
    productKind: 'job-pack',
    previewImage: '/product-previews/ufh-screed-dry-out-log-template.png',
    checkoutUrl: 'https://buy.stripe.com/14A5kC4Qf2RG6yUeK63ks02',
    jobMoment: 'The screed has cured and the heating-up programme is about to begin. You need a day-by-day record that follows the project and manufacturer instructions and can be handed to the client or flooring contractor.',
    sourceNote: 'Set the programme from the current screed, UFH and heat-source manufacturers’ instructions. The workbook deliberately does not prescribe universal temperatures or timings.',
    softwareRequirement: 'Microsoft Excel or compatible spreadsheet software',
    includedItems: ['Editable UFH dry-out Excel workbook', 'Daily flow and return temperature log', 'Floor and room temperature fields', 'Target-temperature and pressure record', 'Observations, actions and installer initials', 'Completed example plus built-in instructions'],
    symbolCategories: ['Project details', 'Programme day', 'Time of reading', 'Flow temperature', 'Return temperature', 'Floor temperature', 'Room temperature', 'Target flow temperature', 'System pressure', 'Observation and sign-off'],
    compatibleWith: ['Microsoft Excel', 'Excel Online', 'Google Sheets import'],
    useCases: ['Underfloor-heating installers', 'Screed contractors', 'Heat-pump installers', 'Flooring contractors checking handover evidence'],
    fileFormats: ['XLSX workbook'],
    installSteps: ['Download and save the original Excel file.', 'Create a project copy and complete the yellow project fields.', 'Replace the grey example with the first live reading.', 'Record each reading during the approved heating-up programme.', 'Resolve actions and save the completed workbook with the handover documents.'],
    faqs: commonFaqs('UFH Screed Dry-Out Log', 'Use the manufacturer-approved programme and obtain competent advice where required.'),
    seoTitle: 'UFH Screed Dry-Out Log Template | Excel Download',
    seoDescription: 'Download an editable underfloor heating screed dry-out log. Record daily flow, return, floor and room temperatures, pressure and installer sign-off.',
    keywords: ['underfloor heating screed dry out log template', 'UFH screed dry out log', 'underfloor heating commissioning log', 'screed heating up protocol template', 'UFH temperature log Excel'],
    relatedSlugs: ['ufh-loop-commissioning-sheet-template', 'heat-pump-flow-rate-commissioning-record-template', 'bluebeam-hvac-mechanical-tool-set'],
  },
  {
    slug: 'soil-stack-air-test-certificate-template',
    title: 'Soil Stack Air Test Certificate Template',
    shortDescription: 'Editable first-fix drainage test register for stack references, test pressure, times, observed loss, result, witness, photographs, and defects.',
    fullDescription: 'Create a clear record before soil stacks and above-ground drainage are boxed in. The workbook keeps each plot, stack or zone tied to the test method, readings, result, witness, photographs, and any remedial action.',
    category: 'Plumbing Records',
    categorySlug: 'plumbing-records',
    price: 15,
    productKind: 'job-pack',
    previewImage: '/product-previews/soil-stack-air-test-certificate-template.png',
    checkoutUrl: 'https://buy.stripe.com/5kQbJ00zZ77WaPagSe3ks03',
    jobMoment: 'The first-fix drainage is installed and is about to be enclosed. You need a test record that a site manager can witness and that still identifies the exact stack or zone months later.',
    sourceNote: 'Enter the test method and acceptance requirements from the approved project specification. This template records the test; it does not tell an unqualified person how to carry it out.',
    softwareRequirement: 'Microsoft Excel or compatible spreadsheet software',
    includedItems: ['Editable air-test certificate workbook', 'Plot, area, stack and zone references', 'Pressure, start, finish and loss fields', 'Pass/fail and witness record', 'Photo and defect references', 'Completed example plus built-in instructions'],
    symbolCategories: ['Test date', 'Plot or area', 'Stack or zone reference', 'Test method', 'Test pressure', 'Start and finish times', 'Observed loss', 'Result', 'Witness', 'Defect and remedial action'],
    compatibleWith: ['Microsoft Excel', 'Excel Online', 'Google Sheets import'],
    useCases: ['Plumbing contractors', 'Housing developers', 'Site managers witnessing tests', 'MEP quality teams'],
    fileFormats: ['XLSX workbook'],
    installSteps: ['Download the Excel workbook.', 'Enter the project, contractor and specification reference.', 'Create one row for each tested stack or zone.', 'Record the test values, result, witness and photo reference.', 'Close defects and save the record before pipework is enclosed.'],
    faqs: commonFaqs('Soil Stack Air Test Certificate', 'The project specification and applicable requirements determine how testing is performed and accepted.'),
    seoTitle: 'Soil Stack Air Test Certificate Template | Excel',
    seoDescription: 'Download an editable soil stack air test certificate template for first-fix drainage. Record pressure, times, results, witness, photos and remedial work.',
    keywords: ['soil stack air test certificate template', 'soil pipe air test certificate', 'drainage air test certificate template', 'above ground drainage test sheet', 'soil stack pressure test record'],
    relatedSlugs: ['cavity-tray-inspection-photo-record-template', 'ground-floor-slab-pre-pour-checklist-uk', 'bluebeam-plumbing-tool-set'],
  },
  {
    slug: 'cavity-tray-inspection-photo-record-template',
    title: 'Cavity Tray Inspection Photo Record Template',
    shortDescription: 'Plot-by-plot Excel register for cavity trays, stop ends, laps, weep holes, cavity cleanliness, photographs, status, and close-out actions.',
    fullDescription: 'Capture the work while it is still visible. This editable register helps brickwork and QA teams connect every opening or elevation to the approved detail, inspection result, before-and-after photographs, and close-out evidence.',
    category: 'Masonry QA',
    categorySlug: 'masonry-qa',
    price: 19,
    productKind: 'job-pack',
    previewImage: '/product-previews/cavity-tray-inspection-photo-record-template.png',
    checkoutUrl: 'https://buy.stripe.com/8x214mciHbocaPagSe3ks04',
    jobMoment: 'Brickwork is rising and trays, laps, stop ends, weep holes, and the cavity will soon be hidden. You need photographic evidence tied to the correct plot and drawing detail before the next lift proceeds.',
    sourceNote: 'Inspect against the approved drawings, warranty-provider requirements and manufacturer instructions. The workbook does not select or design a cavity-tray detail.',
    softwareRequirement: 'Microsoft Excel or compatible spreadsheet software',
    includedItems: ['Editable plot-by-plot Excel register', 'Opening, elevation and drawing-detail fields', 'Tray, stop-end, lap and weep-hole checks', 'Cavity-cleanliness record', 'Before-and-after photo references', 'Status, action and close-out columns'],
    symbolCategories: ['Inspection date', 'Plot', 'Elevation or opening', 'Drawing detail', 'Tray type', 'Stop ends', 'Laps', 'Weep holes', 'Cavity cleanliness', 'Photo and close-out evidence'],
    compatibleWith: ['Microsoft Excel', 'Excel Online', 'Google Sheets import'],
    useCases: ['Brickwork contractors', 'Housing site managers', 'Clerks of works', 'Developer and warranty QA teams'],
    fileFormats: ['XLSX workbook'],
    installSteps: ['Download and create a project copy.', 'Enter the development, contractor and QA reference.', 'Add one row for each elevation or opening inspected.', 'Record checks and use matching photo filenames.', 'Close actions before the detail becomes inaccessible.'],
    faqs: commonFaqs('Cavity Tray Inspection Photo Record', 'A competent person must check the installation against the approved project detail.'),
    seoTitle: 'Cavity Tray Inspection Photo Record Template | Excel',
    seoDescription: 'Download a cavity tray inspection photo record for plots, openings, stop ends, laps, weep holes, cavity checks, photos and close-out evidence.',
    keywords: ['cavity tray inspection photo record template', 'cavity tray inspection checklist', 'weep hole inspection record', 'brickwork photo inspection template', 'cavity tray QA sheet'],
    relatedSlugs: ['ground-floor-slab-pre-pour-checklist-uk', 'roof-truss-bracing-inspection-record-template', 'fire-door-installation-evidence-pack-template'],
  },
  {
    slug: 'firestop-penetration-evidence-register-template',
    title: 'Firestop Penetration Evidence Register Template',
    shortDescription: 'Editable Excel schedule linking each penetration to its rated barrier, approved system, annular space, product batch, installer, photographs, and QC status.',
    fullDescription: 'Keep installation evidence attached to the exact penetration it belongs to. The register gives firestopping contractors and quality teams one structured schedule for system references, field dimensions, named products, batches, photo evidence, inspection status, and deviations.',
    category: 'Firestopping QA',
    categorySlug: 'firestopping-qa',
    price: 29,
    productKind: 'job-pack',
    previewImage: '/product-previews/firestop-penetration-evidence-register-template.png',
    checkoutUrl: 'https://buy.stripe.com/5kQ3cufuT77W3mI59w3ks05',
    jobMoment: 'Services are penetrating rated walls or floors and the installation is about to be closed up. You must prove which approved system was used, what was installed, and where the supporting photographs are stored.',
    sourceNote: 'Only a competent person should select and approve the firestop system. Every field condition must match the approved tested or assessed system; record deviations for formal resolution.',
    softwareRequirement: 'Microsoft Excel or compatible spreadsheet software',
    includedItems: ['Editable firestop penetration schedule', 'Barrier, rating and penetrant record', 'Approved-system and annular-space fields', 'Product and batch traceability', 'Pre-close and finished-photo references', 'QC status plus deviation tracker'],
    symbolCategories: ['Unique penetration ID', 'Floor and room', 'Barrier and rating', 'Penetrant and size', 'Approved system reference', 'Annular space', 'Product and batch', 'Installer and date', 'Before-and-after photographs', 'QC and deviations'],
    compatibleWith: ['Microsoft Excel', 'Excel Online', 'Google Sheets import'],
    useCases: ['Firestopping installers', 'Principal-contractor QA teams', 'MEP coordinators', 'Handover-documentation teams'],
    fileFormats: ['XLSX workbook'],
    installSteps: ['Download and create a project copy.', 'Enter the contractors and inspection-plan reference.', 'Assign a unique ID to each penetration.', 'Record approved-system details and matching photos.', 'Resolve every deviation before QC sign-off and handover.'],
    faqs: commonFaqs('Firestop Penetration Evidence Register', 'System selection, installation and inspection must be performed by competent people using approved evidence.'),
    seoTitle: 'Firestop Penetration Evidence Register Template',
    seoDescription: 'Download an editable firestop penetration register for system references, annular space, product batches, installers, photos, QC status and deviations.',
    keywords: ['firestop penetration evidence register template', 'fire stopping penetration schedule template', 'firestop photo register', 'fire stopping installation record', 'fire penetration log Excel'],
    relatedSlugs: ['fire-door-installation-evidence-pack-template', 'ground-floor-slab-pre-pour-checklist-uk', 'bluebeam-fire-alarm-symbols'],
  },
  {
    slug: 'ufh-loop-commissioning-sheet-template',
    title: 'Underfloor Heating Loop Commissioning Sheet Template',
    shortDescription: 'Editable manifold schedule for design and actual flow rates, loop temperatures, calculated delta-T, actuator checks, final settings, and completion status.',
    fullDescription: 'Balance and hand over each circuit with a record that can be read later. The workbook keeps manifold and loop identity beside design flow, actual flow, supply and return temperatures, calculated temperature difference, actuator checks, and final settings.',
    category: 'Heating Records',
    categorySlug: 'heating-records',
    price: 19,
    productKind: 'job-pack',
    previewImage: '/product-previews/ufh-loop-commissioning-sheet-template.png',
    checkoutUrl: 'https://buy.stripe.com/6oU4gy5Uj63Se1meK63ks06',
    jobMoment: 'The UFH system is filled, vented, and ready to balance. You need to record every loop against its room and design setting before handing the system to the client or heat-source engineer.',
    sourceNote: 'Use the approved design flow rates and manufacturer instructions. The workbook calculates ΔT from entered flow and return temperatures but does not decide whether a setting is acceptable.',
    softwareRequirement: 'Microsoft Excel or compatible spreadsheet software',
    includedItems: ['Editable manifold and loop schedule', 'Design-versus-actual flow-rate fields', 'Flow and return temperature record', 'Automatic ΔT calculation', 'Actuator checks and final settings', 'Automatic record-completeness prompt'],
    symbolCategories: ['Manifold reference', 'Loop number', 'Room or zone', 'Loop length', 'Design flow rate', 'Actual flow rate', 'Flow temperature', 'Return temperature', 'Calculated ΔT', 'Actuator and final setting'],
    compatibleWith: ['Microsoft Excel', 'Excel Online', 'Google Sheets import'],
    useCases: ['UFH installers', 'Heating engineers', 'Heat-pump installers', 'Commissioning and handover teams'],
    fileFormats: ['XLSX workbook with formulas'],
    installSteps: ['Download and create a project copy.', 'Enter the project and approved design reference.', 'Add each loop in manifold order.', 'Enter measured flows, temperatures and final settings.', 'Review incomplete records before customer handover.'],
    faqs: commonFaqs('UFH Loop Commissioning Sheet', 'Use approved design values and manufacturer instructions when balancing the system.'),
    seoTitle: 'UFH Loop Commissioning Sheet Template | Excel',
    seoDescription: 'Download an editable UFH loop commissioning sheet with design and actual flows, temperatures, automatic delta-T, actuator checks and final settings.',
    keywords: ['underfloor heating loop commissioning sheet template', 'UFH manifold commissioning sheet', 'underfloor heating balancing sheet', 'UFH flow rate record', 'UFH loop schedule Excel'],
    relatedSlugs: ['ufh-screed-dry-out-log-template', 'heat-pump-flow-rate-commissioning-record-template', 'bluebeam-hvac-mechanical-tool-set'],
  },
  {
    slug: 'ground-floor-slab-pre-pour-checklist-uk',
    title: 'Ground-Floor Slab Pre-Pour Checklist UK',
    shortDescription: 'Editable Excel checklist for DPM, insulation, reinforcement, service penetrations, photographs, open actions, owners, and close-out evidence.',
    fullDescription: 'Complete one disciplined review before the concrete arrives. This workbook keeps the approved requirement, observed condition, photograph, status, action owner, and close-out evidence together for every item that will disappear beneath the slab.',
    category: 'Concrete QA',
    categorySlug: 'concrete-qa',
    price: 19,
    productKind: 'job-pack',
    previewImage: '/product-previews/ground-floor-slab-pre-pour-checklist-uk.png',
    checkoutUrl: 'https://buy.stripe.com/dRmbJ02I79g49L6eK63ks07',
    jobMoment: 'The slab pour is booked and the DPM, insulation, reinforcement, radon measures, and service penetrations are about to become inaccessible. Open actions must be visible and closed before concrete placement.',
    sourceNote: 'Build the checklist from the approved structural drawings, architectural details, inspection plan, radon strategy where applicable, and product instructions. Required approvals vary by project.',
    softwareRequirement: 'Microsoft Excel or compatible spreadsheet software',
    includedItems: ['Editable UK pre-pour workbook', 'Requirement-versus-observation fields', 'Drawing and specification references', 'Photo evidence register', 'Open-action owner and deadline fields', 'Close-out evidence column'],
    symbolCategories: ['DPM and penetrations', 'Insulation continuity', 'Radon barrier where applicable', 'Reinforcement and cover', 'Levels and dimensions', 'Service locations', 'Drawing references', 'Photo evidence', 'Open actions', 'Close-out approval'],
    compatibleWith: ['Microsoft Excel', 'Excel Online', 'Google Sheets import'],
    useCases: ['Groundworks contractors', 'Site managers', 'Clerks of works', 'Housing and concrete QA teams'],
    fileFormats: ['XLSX workbook'],
    installSteps: ['Download and create a project copy.', 'Enter the plot, contractor, inspector and pour date.', 'Add project-specific checks from approved documents.', 'Record observations, photos, status and action owners.', 'Close every required action before authorising the pour.'],
    faqs: commonFaqs('Ground-Floor Slab Pre-Pour Checklist', 'The project team and competent inspectors determine the checks and approvals required before pouring.'),
    seoTitle: 'Ground Floor Slab Pre-Pour Checklist UK | Excel',
    seoDescription: 'Download a UK ground-floor slab pre-pour checklist for DPM, insulation, reinforcement, services, photos, open actions and close-out evidence.',
    keywords: ['ground floor slab pre pour inspection checklist UK', 'slab pre pour checklist UK', 'DPM inspection checklist', 'concrete slab inspection sheet', 'pre concrete pour checklist Excel'],
    relatedSlugs: ['cavity-tray-inspection-photo-record-template', 'roof-truss-bracing-inspection-record-template', 'firestop-penetration-evidence-register-template'],
  },
  {
    slug: 'fire-door-installation-evidence-pack-template',
    title: 'Fire Door Installation Evidence Pack Template',
    shortDescription: 'Door-by-door Excel register for certificates, labels, frame and fixing evidence, ironmongery, clearances, closer tests, photographs, and defects.',
    fullDescription: 'Build a usable handover record one doorset at a time. This workbook keeps each door ID and location connected to its approved rating, certification, label, installation evidence, ironmongery, measured gaps, closer test, photographs, and outstanding actions.',
    category: 'Fire Door QA',
    categorySlug: 'fire-door-qa',
    price: 29,
    productKind: 'job-pack',
    previewImage: '/product-previews/fire-door-installation-evidence-pack-template.png',
    checkoutUrl: 'https://buy.stripe.com/7sYcN44Qfdwk2iEeK63ks08',
    jobMoment: 'Fire doors are being installed or prepared for handover. You need traceable evidence for each individual doorset—not a generic tick sheet that loses the certificate, ironmongery, photograph, or defect history.',
    sourceNote: 'A competent person must inspect against the approved doorset specification, certification and current fire-safety requirements. The workbook is not a fire-door certificate.',
    softwareRequirement: 'Microsoft Excel or compatible spreadsheet software',
    includedItems: ['Editable door-by-door evidence register', 'Rating and certification references', 'Label, frame and fixing evidence', 'Ironmongery, gaps and closer-test fields', 'Photo-set and installer traceability', 'Inspection status and defect close-out'],
    symbolCategories: ['Door ID', 'Location', 'Rating and smoke control', 'Certificate reference', 'Label or plug', 'Frame and fixing evidence', 'Ironmongery set', 'Recorded gaps', 'Closer test', 'Photographs and defects'],
    compatibleWith: ['Microsoft Excel', 'Excel Online', 'Google Sheets import'],
    useCases: ['Fire-door installers', 'Passive-fire contractors', 'Principal-contractor QA teams', 'Building handover teams'],
    fileFormats: ['XLSX workbook'],
    installSteps: ['Download and create a building or project copy.', 'Enter the installer, inspector and door-schedule revision.', 'Add every doorset using the project door ID.', 'Attach consistent certificate and photo references.', 'Close defects before competent sign-off and handover.'],
    faqs: commonFaqs('Fire Door Installation Evidence Pack', 'Inspection and certification must be undertaken by appropriately competent people.'),
    seoTitle: 'Fire Door Installation Evidence Pack Template',
    seoDescription: 'Download an editable fire-door installation evidence pack for certificates, labels, fixings, ironmongery, gaps, closer tests, photos and defects.',
    keywords: ['fire door installation evidence pack template', 'fire door installation photo record', 'fire door handover pack template', 'fire door register Excel', 'fire door installation checklist'],
    relatedSlugs: ['firestop-penetration-evidence-register-template', 'cavity-tray-inspection-photo-record-template', 'ground-floor-slab-pre-pour-checklist-uk'],
  },
  {
    slug: 'excavation-after-rain-inspection-form-template',
    title: 'Excavation After-Rain Inspection Form Template',
    shortDescription: 'Editable UK inspection record for shift-start and event-triggered checks, identified risks, immediate action, further action, and safe-to-work status.',
    fullDescription: 'Record the inspection that cannot wait until later. This workbook gives a competent person a structured report for the excavation location, inspection trigger, supports or battering, ground and edges, water, access, services, risks, actions, and safe-to-work decision.',
    category: 'Site Safety Records',
    categorySlug: 'site-safety-records',
    price: 15,
    productKind: 'job-pack',
    previewImage: '/product-previews/excavation-after-rain-inspection-form-template.png',
    checkoutUrl: 'https://buy.stripe.com/14A8wO6YncsgaPa9pM3ks09',
    jobMoment: 'Rainfall or another event may have affected an excavation’s stability, or a new shift is starting. A competent person must inspect and record the condition before work proceeds.',
    sourceNote: 'UK HSE guidance states that excavations should be inspected at the start of each shift and after events affecting stability, with written reports following most inspections. Work must not proceed until safe.',
    softwareRequirement: 'Microsoft Excel or compatible spreadsheet software',
    includedItems: ['Editable inspection-report workbook', 'Shift-start and after-event trigger field', 'Supports, ground, water and access checks', 'Services and identified-risk record', 'Immediate and further-action columns', 'Inspector position and safe-to-work decision'],
    symbolCategories: ['Date and time', 'Excavation location', 'Inspection trigger', 'Supports or battering', 'Ground and edges', 'Water ingress', 'Access and egress', 'Services', 'Risks and actions', 'Inspector and safe-to-work status'],
    compatibleWith: ['Microsoft Excel', 'Excel Online', 'Google Sheets import'],
    useCases: ['Competent excavation inspectors', 'Groundworks contractors', 'Site managers', 'Principal-contractor safety teams'],
    fileFormats: ['XLSX workbook'],
    installSteps: ['Download and create a project copy.', 'Enter who the inspection is for and the report reference.', 'Create a row for the shift or event-triggered inspection.', 'Record risks and actions immediately.', 'Do not mark safe to work until the competent person is satisfied.'],
    faqs: commonFaqs('Excavation After-Rain Inspection Form', 'UK HSE requires inspection by a competent person and work must not proceed until the excavation is safe.'),
    seoTitle: 'Excavation After-Rain Inspection Form Template UK',
    seoDescription: 'Download a UK excavation after-rain inspection form for stability checks, risks, immediate actions, further actions and safe-to-work status.',
    keywords: ['excavation inspection after rain form', 'excavation after rainfall inspection template', 'excavation daily inspection report UK', 'trench inspection form after rain', 'excavation inspection Excel'],
    relatedSlugs: ['ground-floor-slab-pre-pour-checklist-uk', 'roof-truss-bracing-inspection-record-template', 'cavity-tray-inspection-photo-record-template'],
  },
  {
    slug: 'heat-pump-flow-rate-commissioning-record-template',
    title: 'Heat Pump Flow-Rate Commissioning Record Template',
    shortDescription: 'Editable water-side baseline for flow rate, flow and return temperatures, automatic delta-T, pump setting, weather curve, pressure, and treatment.',
    fullDescription: 'Leave a commissioning baseline that makes the next visit easier. The workbook records outdoor conditions, operating mode, water-side temperatures, calculated temperature difference, measured flow, pump setting, weather curve, pressure, water treatment, and adjustments.',
    category: 'Heat Pump Records',
    categorySlug: 'heat-pump-records',
    price: 25,
    productKind: 'job-pack',
    previewImage: '/product-previews/heat-pump-flow-rate-commissioning-record-template.png',
    checkoutUrl: 'https://buy.stripe.com/bJecN4aaz2RG3mI9pM3ks0a',
    jobMoment: 'The heat pump is being commissioned or investigated and you need a reliable water-side baseline. Without recorded flow, temperatures, settings, pressure, and treatment, later callbacks become guesswork.',
    sourceNote: 'Use the heat-pump manufacturer’s commissioning sheet and current MCS or project requirements. This supplementary record does not replace mandatory commissioning or certification documents.',
    softwareRequirement: 'Microsoft Excel or compatible spreadsheet software',
    includedItems: ['Editable heat-pump commissioning workbook', 'Operating mode and outdoor-temperature fields', 'Flow, return and automatic ΔT calculation', 'Measured flow and pump-setting record', 'Weather-curve, pressure and treatment fields', 'Adjustment notes and engineer traceability'],
    symbolCategories: ['Date and operating mode', 'Outdoor temperature', 'Flow temperature', 'Return temperature', 'Calculated ΔT', 'Measured flow rate', 'Pump setting', 'Weather-compensation curve', 'System pressure', 'Water treatment and adjustments'],
    compatibleWith: ['Microsoft Excel', 'Excel Online', 'Google Sheets import'],
    useCases: ['Heat-pump installers', 'MCS contractors', 'Heating commissioning engineers', 'Service and diagnostic technicians'],
    fileFormats: ['XLSX workbook with formulas'],
    installSteps: ['Download and create a property copy.', 'Enter the heat pump, installer and design references.', 'Record readings at stable operating conditions.', 'Save every setting change and observation.', 'Include the completed baseline with customer handover records.'],
    faqs: commonFaqs('Heat Pump Flow-Rate Commissioning Record', 'Follow the manufacturer’s required procedure and all applicable commissioning requirements.'),
    seoTitle: 'Heat Pump Flow-Rate Commissioning Record | Excel',
    seoDescription: 'Download a heat-pump flow-rate commissioning record with temperatures, automatic delta-T, flow, pump setting, weather curve, pressure and treatment.',
    keywords: ['heat pump commissioning flow rate record template', 'heat pump flow rate commissioning sheet', 'heat pump delta T log', 'ASHP commissioning record Excel', 'heat pump water side commissioning template'],
    relatedSlugs: ['ufh-loop-commissioning-sheet-template', 'ufh-screed-dry-out-log-template', 'bluebeam-hvac-mechanical-tool-set'],
  },
  {
    slug: 'roof-truss-bracing-inspection-record-template',
    title: 'Roof Truss Bracing Inspection Record Template',
    shortDescription: 'Editable pre-cover register for truss drawing revisions, areas, required details, observed conditions, photos, open actions, designer queries, and approval.',
    fullDescription: 'Keep the roof inspection tied to the drawing that governed the work. This workbook lets roofing and site teams record the exact truss drawing revision, area, item checked, required detail, observed condition, photograph, status, designer query, and close-out approval.',
    category: 'Roofing QA',
    categorySlug: 'roofing-qa',
    price: 19,
    productKind: 'job-pack',
    previewImage: '/product-previews/roof-truss-bracing-inspection-record-template.png',
    checkoutUrl: 'https://buy.stripe.com/5kQaEW96v8c0aPa59w3ks0b',
    jobMoment: 'The trussed roof is erected and bracing details are still visible. Before ceilings, insulation, or other work restricts access, you need drawing-referenced photographs and a clear route for designer queries and close-out.',
    sourceNote: 'Inspect against the truss designer’s current drawings and project specification. Refer structural deviations and questions to the responsible designer; this workbook does not approve structural work.',
    softwareRequirement: 'Microsoft Excel or compatible spreadsheet software',
    includedItems: ['Editable pre-cover Excel register', 'Truss drawing and revision reference', 'Area, grid and item-checked fields', 'Requirement-versus-observation record', 'Photo, status and designer-query columns', 'Close-out approval and inspector traceability'],
    symbolCategories: ['Inspection date', 'Plot or roof', 'Truss drawing revision', 'Area or grid', 'Item checked', 'Required detail', 'Observed condition', 'Photo reference', 'Designer query', 'Close-out and inspector'],
    compatibleWith: ['Microsoft Excel', 'Excel Online', 'Google Sheets import'],
    useCases: ['Roofing contractors', 'Timber-frame contractors', 'Site managers', 'Housing QA and handover teams'],
    fileFormats: ['XLSX workbook'],
    installSteps: ['Download and create a project copy.', 'Enter the contractor, inspector and truss designer.', 'Confirm and record the current drawing revision.', 'Add each inspected area, observation and photo reference.', 'Resolve designer queries before close-out or covering the work.'],
    faqs: commonFaqs('Roof Truss Bracing Inspection Record', 'A competent person must inspect against the current truss design, and the responsible designer must resolve structural deviations.'),
    seoTitle: 'Roof Truss Bracing Inspection Record Template',
    seoDescription: 'Download an editable roof-truss bracing inspection record for drawing revisions, site observations, photos, designer queries and pre-cover close-out.',
    keywords: ['roof truss bracing inspection record template', 'roof truss inspection checklist', 'truss bracing sign off sheet', 'roof pre cover inspection record', 'roof truss photo record Excel'],
    relatedSlugs: ['ground-floor-slab-pre-pour-checklist-uk', 'cavity-tray-inspection-photo-record-template', 'fire-door-installation-evidence-pack-template'],
  },
];
