from __future__ import annotations

PAGE_FIELDS = [
    "source_domain",
    "source_url",
    "canonical_url",
    "http_status",
    "page_type",
    "title",
    "meta_description",
    "h1",
    "h2_list",
    "h3_list",
    "word_count",
    "detected_language",
    "crawl_timestamp",
    "robots_allowed",
    "canonical_duplicate_of",
    "notes",
]

PRODUCT_FIELDS = [
    "source_domain",
    "source_url",
    "product_name",
    "product_category",
    "discipline",
    "trade",
    "software_context",
    "price",
    "currency",
    "sale_price",
    "number_of_symbols_claimed",
    "file_types_mentioned",
    "delivery_method",
    "compatibility_claims",
    "included_items_summary",
    "license_notes",
    "refund_notes",
    "faq_questions",
    "trust_signals",
    "reviews_count",
    "rating",
    "cta_text",
    "source_evidence_short",
]

SEO_FIELDS = [
    "keyword",
    "intent",
    "buyer_stage",
    "page_target",
    "difficulty_proxy",
    "commercial_value_proxy",
    "source_evidence",
    "recommended_url",
    "recommended_title",
    "recommended_h1",
]

COMPETITOR_FIELDS = [
    "competitor",
    "domain",
    "categories_covered",
    "pricing_range",
    "free_sample",
    "number_of_product_pages_found",
    "number_of_guide_pages_found",
    "strongest_pages",
    "weaknesses",
    "opportunities_for_us",
    "design_notes",
    "seo_notes",
]

TAXONOMY_KEYS = [
    "electrical",
    "fire alarm",
    "CCTV",
    "access control",
    "security",
    "AV/audio-visual",
    "telecom/data",
    "lighting",
    "HVAC/mechanical",
    "plumbing",
    "structural",
    "architectural",
    "landscaping/site planning",
    "traffic/MUTCD",
    "estimating/takeoff",
    "general Bluebeam workflow",
    "free samples",
    "tutorials/how-to guides",
]

DISCIPLINE_KEYWORDS = {
    "electrical": ["electrical", "electrician", "conduit", "power", "lighting"],
    "fire alarm": ["fire alarm", "fa ", "alarm", "notification", "detector"],
    "CCTV": ["cctv", "camera", "surveillance", "video"],
    "access control": ["access control", "card reader", "door", "credential"],
    "security": ["security", "intrusion", "alarm", "sensor"],
    "AV/audio-visual": ["av", "audio", "visual", "speaker", "display", "rack"],
    "telecom/data": ["telecom", "data", "network", "cabling", "low voltage"],
    "lighting": ["lighting", "luminaire", "fixture"],
    "HVAC/mechanical": ["hvac", "mechanical", "duct", "diffuser"],
    "plumbing": ["plumbing", "pipe", "valve"],
    "structural": ["structural", "steel", "concrete"],
    "architectural": ["architectural", "door", "window", "wall"],
    "landscaping/site planning": ["landscape", "site planning", "site plan"],
    "traffic/MUTCD": ["traffic", "mutcd", "road", "sign"],
    "estimating/takeoff": ["estimating", "takeoff", "quantity", "measurement"],
    "general Bluebeam workflow": ["bluebeam", "revu", "tool chest", "tool set"],
    "free samples": ["free", "sample"],
    "tutorials/how-to guides": ["how to", "guide", "tutorial", "tips"],
}
